---
# ansible-role-clamav (geerlingguy.clamav) vars.

# These are default values.
clamav_daemon_state: started
clamav_daemon_enabled: true
clamav_freshclam_daemon_state: started
clamav_freshclam_daemon_enabled: true
clamav_daemon_configuration_changes:
  # At least in the context of Molecule, the default 30s value is too short
  # and causes test failures.
  - regexp: "^ReceiveTimeout"
    line: "ReceiveTimeout 120"
