---
# ansible-role-security (geerlingguy.security) vars.

security_ssh_port: "{{ rdev_ssh_port }}"
security_sudoers_passwordless:
  - "{{ rdev_user }}"
# Unattended Upgrades managed by ansible-role-unattended-upgrades.
security_autoupdate_enabled: false
security_fail2ban_enabled: false
