---
- name: Converge
  hosts: all

  collections:
    - ctorgalson.remote_dev

  tasks:
    # Vars in group_vars/all/ansible-environment.yml.
    - name: Set environment variables.
      import_role:
        name: "ansible-environment"

    # Vars in group_vars/all/ansible-role-apt.yml.
    - name: Install required packages.
      import_role:
        name: "ansible-role-apt"

    # Vars in group_vars/all/ansible-users.yml.
    - name: Set up required users.
      import_role:
        name: "ansible-users"
