---
- name: Converge
  hosts: all

  collections:
    - ctorgalson.remote_dev

  tasks:
    # Vars in group_vars/all/ansible-environment.yml.
    - name: Set environment variables.
      import_role:
        name: "ansible-environment"

    # Vars in group_vars/all/ansible-role-apt.yml.
    - name: Install required packages.
      import_role:
        name: "ansible-role-apt"

    # Vars in group_vars/all/ansible-users.yml.
    - name: Set up required users.
      import_role:
        name: "ansible-users"

    # Vars in group_vars/all/ansible-role-oh-my-zsh.yml.

    # Vars in group_vars/all/ansible-role-ssh-keys.yml.
    - name: Set up user ssh keys.
      import_role:
        name: "ansible-role-ssh-keys"

    # Vars in group_vars/all/ansible-role-dotfiles.yml.
    - name: Set up dotfiles in user home directory.
      import_role:
        name: "ansible-role-dotfiles"

    # Vars in group_vars/all/ansible-role-files.yml.
    - name: Set up file structure in user home directory.
      import_role:
        name: "ansible-role-files"

    # Vars in group_vars/all/ansible-role-security.yml.
    - name: Set up basic system security.
      import_role:
        name: "ansible-role-security"

    # Vars in group_vars/all/ansible-role-firewall.yml.
    - name: Set up system firewall.
      import_role:
        name: "ansible-role-firewall"
