---
- name: Converge
  hosts: all

  collections:
    - ctorgalson.remote_dev

  tasks:
    # Vars in group_vars/all/ansible-environment.yml.
    - name: Set environment variables.
      import_role:
        name: "ansible-environment"

    # Vars in group_vars/all/ansible-timezone.yml.
    - name: Set system time zone.
      import_role:
        name: "ansible-timezone"

    # Vars in group_vars/all/ansible-role-apt.yml.
    - name: Install required apt packages.
      import_role:
        name: "ansible-role-apt"

    # Vars in group_vars/all/ansible-role-pip.yml.
    - name: Install required pip packages.
      import_role:
        name: "ansible-role-pip"

    # Vars in group_vars/all/ansible-users.yml.
    - name: Set up required users.
      import_role:
        name: "ansible-users"

    # Vars in group_vars/all/ansible-role-oh-my-zsh.yml.
    - name: Set up zsh and oh-my-zsh for user.
      import_role:
        name: "ansible-role-oh-my-zsh"

    # Vars in group_vars/all/ansible-role-vim.yml.
    - name: Set up Vim and its plugins.
      import_role:
        name: "ansible-role-vim"

    # Vars in group_vars/all/ansible-role-ssh-keys.yml.
    - name: Set up user ssh keys.
      import_role:
        name: "ansible-role-ssh-keys"

    # Vars in group_vars/all/ansible-role-dotfiles.yml.
    - name: Set up dotfiles in user home directory.
      import_role:
        name: "ansible-role-dotfiles"

    # Vars in group_vars/all/ansible-role-files.yml.
    - name: Set up file structure in user home directory.
      import_role:
        name: "ansible-role-files"

    # Vars in group_vars/all/ansible-role-security.yml.
    - name: Set up basic system security.
      import_role:
        name: "ansible-role-security"

    # Vars in group_vars/all/ansible-role-firewall.yml.
    - name: Set up system firewall.
      import_role:
        name: "ansible-role-firewall"

    # Vars in group_vars/all/ansible-role-php.yml.
    - name: Set up php for composer/cli use.
      import_role:
        name: "ansible-role-php"

    # Vars in group_vars/all/ansible-role-composer.yml.
    - name: Set up composer.
      import_role:
        name: "ansible-role-composer"

    # Vars in group_vars/all/ansible-role-nodejs.yml.
    - name: Set up nodejs.
      import_role:
        name: "ansible-role-nodejs"

    # Vars in group_vars/all/ansible-role-yarn.yml.

    # Vars in group_vars/all/ansible-role-nvm.yml.

    # Vars in group_vars/all/ansible-role-docker.yml.
