---
dependency:
  name: galaxy
lint: |
  ./scripts/lint.sh
env:
  ANSIBLE_COLLECTIONS_PATHS: "../ctorgalson"
driver:
  name: docker
platforms:
  - name: instance
    image: geerlingguy/docker-ubuntu1804-ansible:latest
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
