---
dependency:
  name: galaxy
lint: |
  pwd && ls -hal ./scripts
  ./scripts/lint.sh
env:
  ANSIBLE_COLLECTIONS_PATHS: "../ctorgalson:/home/runner/ansible_collections/ctorgalson"
driver:
  name: docker
platforms:
  - name: instance
    image: geerlingguy/docker-ubuntu1804-ansible:latest
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  inventory:
    links:
      group_vars: ../group_vars
verifier:
  name: testinfra
  directory: ../../tests/default
