---
dependency:
  name: galaxy
lint: |
  ./scripts/lint.sh
driver:
  name: docker
platforms:
  - name: instance
    image: geerlingguy/docker-ubuntu1804-ansible:latest
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
    groups:
      - docksal_mosh_sshuttle_vim
provisioner:
  name: ansible
  inventory:
    links:
      group_vars: ../../playbooks/group_vars
    playbooks:
      cleanup: cleanup.yml
      converge: converge.yml
      prepare: prepare.yml
  env:
    ANSIBLE_COLLECTIONS_PATHS: "~/.ansible/collections"
verifier:
  name: testinfra
  directory: ../../tests/default
